### PR TITLE
Master

### PR DESCRIPTION
**Pull request by aa-savelyev**
Typo: unnecessary indent in cycle

### CODE REVIEW

**Comment by aa-savelyev** [comment]
Oh, I am sorry!
I meant only one commit to pull.
This one: "Typo: unnecessary indent".

**Comment by gforsyth** [comment]
Hey @aa-savelyev -- thanks for the edit!  

So yeah -- you've noticed that when you put in a pull request, it will try to merge in all the commits that are "ahead" of our master branch.  

The trick is to add your fix on top of our master branch and have that be the only commit that's different.  

If you want to try it out, you can follow these steps:

First, jump back in your history to before your first commit by doing

```
git checkout 5f21156
```

You can check `git log` now to make sure that you've moved back in your history.  

Now create a new branch in your fork (maybe called `fix_indent`):
```
git checkout -b fix_indent
```

Now you want to add your indent fixing commit on top of this new branch.  It's a simple commit, so you could just redo it, but the more extensible way is to `cherry-pick` that commit from your master branch.

Note that your Typo commit has the hash 7fc8b9e, so you would run

```
git cherry-pick master 7fc8b9e
```

Now look at your `git log` again and you should see only your Typo commit on top of the commits that existed before you started your working directory.  

Then you can push that branch up to Github

```
git push -u origin fix_indent
```

and start a new pull request without all the other commits mixed in.

**Comment by aa-savelyev** [comment]
Thank you, @gforsyth!
I shuold try it!
Does it proper way to fix typos that i find in notebooks?

**Comment by gforsyth** [comment]
It's a good way to fix typos -- saves us work!  But you can also just open an issue and explain the typo and we can change it.  

Up to you!

**Pull request closed without merging**
