### PR TITLE
Css fixes

### PR DESCRIPTION
**Pull request by IsakFalk**
Fixed some cases where there was tabs instead of spaces and a missing newline. Just so the code is a bit easier to read (and because I am pedantic I guess).

### CODE REVIEW

**Comment by labarba** [comment]
I'm no expert in CSS, so that file is probably a hack of copy-pasted snippets from the web. Any help making the style sheet better is thus appreciated!

**Comment by gforsyth** [comment]
I'm a firm believer in pedantry.  Speaking of which, can you rebase those three commits down into a single shot before we merge?

**Comment by IsakFalk** [comment]
Sure, give me a sec. I'm not really that well versed with Css and/or HTML either, but it's always nice to have neat code!

**Comment by gforsyth** [comment]
Closing this -- merged in #130

**Pull request closed without merging**
