### PR TITLE
Modification based on the code review on 01/30/2015

### PR DESCRIPTION
**Pull request by piyueh**
Modification based on the code review on 01/30/2015

### CODE REVIEW

**Comment by gforsyth** [comment]
Hi @piyueh --

Can you clear output in the notebook before pushing?  It makes it easier to review the diffs.  Thanks!

**Comment by piyueh** [comment]
Sure! Waite a minute

**Comment by piyueh** [comment]
Hi @gforsyth 

Done.

**Comment by gforsyth** [comment]
I'm merging this in so I can get started editing the text, etc...

**Pull request merged**
