### PR TITLE
Corrections of equation numbers

### PR DESCRIPTION
**Pull request by bknaepen**

### CODE REVIEW

**Comment by mesnardo** [comment]
@bknaepen  Regarding the bug fix, I have another possibility for the function `rho_green_light` which I think is easier to read/understand and closer to the mathematical equations:

```python
def rho_green_light(x, rho_max):
    rho = numpy.zeros_like(x)
    mask = numpy.where(x < 2.0)
    rho[mask] = rho_max * x[mask] / 2.0
    return rho
```
What do you think?

**Comment by bknaepen** [comment]
Hi @mesnardo, your suggested change is less minimalistic :-), but I agree it is much easier to read and less prone to mistakes. On top of that, the numpy.where function is explained in detail earlier in the notebooks so there's no reason not to use it...

**Comment by mesnardo** [comment]
Hi @bknaepen, do you mind to add this modification to the present PR? After that, I will merge the PR.

**Comment by mesnardo** [comment]
Thank you @bknaepen.
Last bit, can you update the docstring of the function in the two notebooks to reflect the change in parameters (`nx` -> `x`)? After that, we should be good.

**Comment by mesnardo** [comment]
Merging now.
I will change the docstring of the function.

**Comment by mesnardo** [comment]
Updated docstrings with commit 48b7ca6.

**Pull request merged**
