### PR TITLE
Suggestions for some little improvements in the phugoid oscillation notebook.

### PR DESCRIPTION
**Pull request by bknaepen**
The suggested changes are listed in the commit message of the penultimate commit.

### CODE REVIEW

**Comment by gforsyth** [comment]
@labarba -- these all look good to me.  

@bknaepen -- thanks for the suggestions!

**Comment by labarba** [comment]
Thanks for contributing! You're right: we should not be reusing variable symbols, and v was used twice ... but so is m! (for mass). So we will need another letter here ...

**Comment by bknaepen** [comment]
As Lorena pointed out, m was already used in the previous pull request. It has now been changed to b.
Two extra modifications have now also been committed in the PhugoidFullModel notebook (see commit message).

**Comment by bknaepen** [comment]
Two further suggestions in the Second_Order_Methods notebook.

**Comment by labarba** [comment]
Thanks!
I'm not convinced about the change of "forward velocity" to "tangential velocity"  (the reader thinks: tangential to what? ah, the trajectory). But I'll merge now and make a small edit later there.

**Pull request merged**
