### PR TITLE
One more typo correction for the cursed formula

### PR DESCRIPTION
**Pull request by bknaepen**

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @bknaepen -- thanks for putting this in. 
I wish it weren't, but I think it's a little more complicated than just adding the `\Delta x^2`. 

The line that calculates the residual reads: 
```python
r[1:-1,1:-1] = b[1:-1,1:-1]*dx**2 + 4*pd[1:-1,1:-1] - pd[1:-1,2:] - pd[1:-1,:-2] - pd[2:, 1:-1] - pd[:-2, 1:-1]
```
which doesn't match the formula if `A = \nabla^2 p`

I think this comes down to whether we discretize when `Ap = b` or when `r = b - Ap'`

If we discretize `Ap = b` (which I think is correct), then we can throw the `\Delta x^2` over to the RHS and have a `A*p = b \Delta x^2` where `A*` is some modified Laplacian without the delta. That would match the code we currently have (and again, I think that's right). But we should probably explain that a little bit, because if `r = b - Ap` and `A` is the discrete Laplacian, then there's an inconsistency with our implementation.

**Comment by bknaepen** [comment]
I fully agree with your remark. To make it simple, why don't I change the implementation so that it truly reflects the original equation?

**Comment by gforsyth** [comment]
Sounds like a plan.

**Comment by bknaepen** [comment]
Ok done. One more check on your side?

**Pull request merged**
